// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPRZXW-B4YcS_IkjDWRS-VDvtCBlzit9A',
    appId: '1:499790913258:web:1c44a1fa2a80632c9d4193',
    messagingSenderId: '499790913258',
    projectId: 'projprimeiro',
    authDomain: 'projprimeiro.firebaseapp.com',
    storageBucket: 'projprimeiro.appspot.com',
    measurementId: 'G-WENLGV9T69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHKrcpqviRJ3nY178AHJsBny-9IDalL1A',
    appId: '1:499790913258:android:4ac67b7b96a9a5f29d4193',
    messagingSenderId: '499790913258',
    projectId: 'projprimeiro',
    storageBucket: 'projprimeiro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2YDgVUEey129NpD4ur8JQN_cXmK_RYEg',
    appId: '1:499790913258:ios:3f39c24ca1de824a9d4193',
    messagingSenderId: '499790913258',
    projectId: 'projprimeiro',
    storageBucket: 'projprimeiro.appspot.com',
    iosBundleId: 'com.example.projetoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2YDgVUEey129NpD4ur8JQN_cXmK_RYEg',
    appId: '1:499790913258:ios:907b00aee2f375f39d4193',
    messagingSenderId: '499790913258',
    projectId: 'projprimeiro',
    storageBucket: 'projprimeiro.appspot.com',
    iosBundleId: 'com.example.projetoFirebase.RunnerTests',
  );
}
